# Generated by Django 5.1.6 on 2025-02-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_blogpost_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
